
// (c) 2023 Kazuki KOHZUKI

// Generated by JsonTemplateMaker and modified by hand.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Symbolix;

#nullable enable

/// <summary>
/// Represents ConfigJson.
/// </summary>
public sealed class ConfigJson
{
    [JsonPropertyName("save")]
    public string[]? Save { get; set; }

    /// <summary>
    /// Gets or sets the check-minus.
    /// </summary>
    [JsonPropertyName("check-minus")]
    public bool? CheckMinus { get; set; }

    /// <summary>
    /// Gets or sets the replace.
    /// </summary>
    [JsonPropertyName("replace")]
    public JsonReplaceElementObject[]? Replace { get; set; }

    /// <summary>
    /// Gets or sets the minus.
    /// </summary>
    [JsonPropertyName("minus")]
    public JsonHyphenReplaceElementObject[]? Minus { get; set; }

    /// <summary>
    /// Gets or sets the en-dash.
    /// </summary>
    [JsonPropertyName("en-dash")]
    public JsonHyphenReplaceElementObject[]? EnDash { get; set; }

    /// <summary>
    /// Gets or sets the em-dash.
    /// </summary>
    [JsonPropertyName("em-dash")]
    public JsonHyphenReplaceElementObject[]? EmDash { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="ConfigJson"/> class.
    /// </summary>
    public ConfigJson() { }

    /// <summary>
    /// Creates a new instance of the <see cref="ConfigJson"/> class from JSON string.
    /// </summary>
    /// <param name="jsonString">JSON text to parse.</param>
    /// <returns>A <see cref="ConfigJson"/> instance representing the JSON value.</returns>
    public static ConfigJson? LoadJson(string jsonString)
        => JsonSerializer.Deserialize<ConfigJson>(jsonString);

    /// <summary>
    /// Represents an element of <see cref="Replace"/>.
    /// </summary>
    public sealed class JsonReplaceElementObject
    {
        /// <summary>
        /// Gets or sets the action.
        /// </summary>
        [JsonPropertyName("action")]
        public string? Action { get; set; }

        /// <summary>
        /// Gets or sets the find.
        /// </summary>
        [JsonPropertyName("find")]
        public string? Find { get; set; }

        /// <summary>
        /// Gets or sets the replace.
        /// </summary>
        [JsonPropertyName("replace")]
        public string? Replace { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="JsonReplaceElementObject"/> class.
        /// </summary>
        public JsonReplaceElementObject() { }
    }

    /// <summary>
    /// Represents an element of <see cref="EnDash"/>.
    /// </summary>
    public sealed class JsonHyphenReplaceElementObject
    {
        /// <summary>
        /// Gets or sets the action.
        /// </summary>
        [JsonPropertyName("action")]
        public string? Action { get; set; }

        /// <summary>
        /// Gets or sets the find.
        /// </summary>
        [JsonPropertyName("find")]
        public string? Find { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="JsonHyphenReplaceElementObject"/> class.
        /// </summary>
        public JsonHyphenReplaceElementObject() { }
    }
}
